export const ACTION_LOADING = 'ACTION_LOADING'
export const ACTION_SUCCESS = 'ACTION_SUCCESS'
export const ACTION_ERROR = 'ACTION_ERROR'

export const GET_ALL_LOADING = 'GET_ALL_LOADING'
export const GET_ALL_SUCCESS = 'GET_ALL_SUCCESS'
export const GET_ALL_ERROR = 'GET_ALL_ERROR'

export const EVENT_CREATED = 'EVENT_CREATED'
export const EVENT_UPDATED = 'EVENT_UPDATED'
export const EVENT_DELETED = 'EVENT_DELETED'
