export const ACTION_LOADING = 'ACTION_LOADING'
export const ACTION_SUCCESS = 'ACTION_SUCCESS'
export const ACTION_ERROR = 'ACTION_ERROR'

export const GET_ALL_LOADING = 'GET_ALL_LOADING'
export const GET_ALL_SUCCESS = 'GET_ALL_SUCCESS'
export const GET_ALL_ERROR = 'GET_ALL_ERROR'

export const EVENT_CREATED = 'EVENT_CREATED'
export const EVENT_UPDATED = 'EVENT_UPDATED'
export const EVENT_DELETED = 'EVENT_DELETED'

export const EVENT_FOCUSED = 'EVENT_FOCUSED'
export const EVENT_UNFOCUSED = 'EVENT_UNFOCUSED'

export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'